# config.yml
###############################################################################
#
#    $$$$$$$$\ $$\      $$\  $$$$$$\   $$$$$$\  $$\
#    $$  _____|$$$\    $$$ |$$  __$$\ $$  __$$\ $$ |
#    $$ |      $$$$\  $$$$ |$$ /  \__|$$ /  \__|$$$$$$$\   $$$$$$\   $$$$$$\
#    $$$$$\    $$\$$\$$ $$ |$$ |      \$$$$$$\  $$  __$$\ $$  __$$\ $$  __$$\
#    $$  __|   $$ \$$$  $$ |$$ |       \____$$\ $$ |  $$ |$$ /  $$ |$$ /  $$ |
#    $$ |      $$ |\$  /$$ |$$ |  $$\ $$\   $$ |$$ |  $$ |$$ |  $$ |$$ |  $$ |
#    $$$$$$$$\ $$ | \_/ $$ |\$$$$$$  |\$$$$$$  |$$ |  $$ |\$$$$$$  |$$$$$$$  |
#    \________|\__|     \__| \______/  \______/ \__|  \__| \______/ $$  ____/
#                                                                   $$ |
#                                                                   $$ |
#                                                                   \__|
#
#    EMCShop - 狐风轩汐 & F.windEmiko
#    插件文档：
#    https://f.windemiko.top/wiki/emcshop
#
###############################################################################

# 经济系统设置
economy:
  # 经济模式: VAULT(使用Vault经济) 或 EMC(使用插件独立经济)
  mode: "EMC"

purchase:
  # 重构损耗率，1表示100%
  reconstruction-loss: 0.038

# 数据库配置（重启服务器以生效）
database:
  # 数据库类型: mysql 或 sqlite
  type: "sqlite"

  # SQLite配置
  file: "emcshop.db"

  # MySQL配置 (当type为mysql时使用)
  host: localhost
  port: 3306
  database: emcshop
  username: root
  password: ''

  # 数据库高级配置（除非你知道这些配置项意味着什么，否则不要乱动哦）
  # 连接池配置
  pool:
    max-size: 8
    min-idle: 2
    connection-timeout: 10000
    idle-timeout: 300000
    max-lifetime: 900000 # 15分钟
    leak-detection-threshold: 15000 # 15秒泄漏检测
    validation-timeout: 3000
  # 数据存储队列（异常场景处理）
  queue:
    batch-size: 100      # 每次处理的最大任务数
    process-interval: 50 # 队列处理间隔(ms)
    save-delay: 10       # 保存操作延迟(ticks)